### ISSUE TITLE
Error when vacuuming all rooms

### ISSUE THREAD

**Issue by drakehomebridge** [RMCob/homebridge-wyze-robovac#21]
**Describe Your Problem:**
When choosing to vacuum all rooms or just one room, the vacuum doesn't start up.

**Logs:**

`[2/1/2024, 6:08:00 PM] [WyzeRoboVac] error: Command failed: python3 /usr/local/lib/node_modules/homebridge-wyze-robovac/py_helpers/getVacuumStatus.py 'Vacuum'
Traceback (most recent call last):
  File "/usr/local/lib/node_modules/homebridge-wyze-robovac/py_helpers/getVacuumStatus.py", line 15, in <module>
    client = Client(email=os.sys.argv[1], password=os.sys.argv[2], key_id=os.sys.argv[3], api_key=os.sys.argv[4])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/wyze_sdk/api/client.py", line 73, in __init__
    self.login()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/wyze_sdk/api/client.py", line 185, in login
    response = self._auth_client().user_login(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/wyze_sdk/service/auth_service.py", line 88, in user_login
    response = self.api_call(
               ^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/wyze_sdk/service/auth_service.py", line 58, in api_call
    return super().api_call(
           ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/wyze_sdk/service/base.py", line 347, in api_call
    return super().api_call(
           ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/wyze_sdk/service/base.py", line 204, in api_call
    return self.do_post(url=api_url, headers=headers, payload=json, params=params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/wyze_sdk/service/base.py", line 132, in do_post
    return self._do_request(client, req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/wyze_sdk/service/base.py", line 106, in _do_request
    raise err
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/wyze_sdk/service/base.py", line 93, in _do_request
    response.raise_for_status()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://auth-prod.api.wyze.com/api/user/login

[2/1/2024, 6:08:15 PM] [WyzeRoboVac] error: Command failed: python3 /usr/local/lib/node_modules/homebridge-wyze-robovac/py_helpers/getVacuumStatus.py  'Vacuum'
Traceback (most recent call last):
  File "/usr/local/lib/node_modules/homebridge-wyze-robovac/py_helpers/getVacuumStatus.py", line 15, in <module>
    client = Client(email=os.sys.argv[1], password=os.sys.argv[2], key_id=os.sys.argv[3], api_key=os.sys.argv[4])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/wyze_sdk/api/client.py", line 73, in __init__
    self.login()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/wyze_sdk/api/client.py", line 185, in login
    response = self._auth_client().user_login(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/wyze_sdk/service/auth_service.py", line 88, in user_login
    response = self.api_call(
               ^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/wyze_sdk/service/auth_service.py", line 58, in api_call
    return super().api_call(
           ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/wyze_sdk/service/base.py", line 347, in api_call
    return super().api_call(
           ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/wyze_sdk/service/base.py", line 204, in api_call
    return self.do_post(url=api_url, headers=headers, payload=json, params=params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/wyze_sdk/service/base.py", line 132, in do_post
    return self._do_request(client, req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/wyze_sdk/service/base.py", line 106, in _do_request
    raise err
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/wyze_sdk/service/base.py", line 93, in _do_request
    response.raise_for_status()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://auth-prod.api.wyze.com/api/user/login

[2/1/2024, 6:08:30 PM] [WyzeRoboVac] error: Command failed: python3 /usr/local/lib/node_modules/homebridge-wyze-robovac/py_helpers/getVacuumStatus.py  'Vacuum'
Traceback (most recent call last):
  File "/usr/local/lib/node_modules/homebridge-wyze-robovac/py_helpers/getVacuumStatus.py", line 15, in <module>
    client = Client(email=os.sys.argv[1], password=os.sys.argv[2], key_id=os.sys.argv[3], api_key=os.sys.argv[4])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/wyze_sdk/api/client.py", line 73, in __init__
    self.login()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/wyze_sdk/api/client.py", line 185, in login
    response = self._auth_client().user_login(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/wyze_sdk/service/auth_service.py", line 88, in user_login
    response = self.api_call(
               ^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/wyze_sdk/service/auth_service.py", line 58, in api_call
    return super().api_call(
           ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/wyze_sdk/service/base.py", line 347, in api_call
    return super().api_call(
           ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/wyze_sdk/service/base.py", line 204, in api_call
    return self.do_post(url=api_url, headers=headers, payload=json, params=params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/wyze_sdk/service/base.py", line 132, in do_post
    return self._do_request(client, req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/wyze_sdk/service/base.py", line 106, in _do_request
    raise err
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/wyze_sdk/service/base.py", line 93, in _do_request
    response.raise_for_status()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://auth-prod.api.wyze.com/api/user/login

[2/1/2024, 6:08:45 PM] [WyzeRoboVac] error: Command failed: python3 /usr/local/lib/node_modules/homebrid`

My email and password are right, and I copy and pasted the Key ID and API Key straight from the Wyze portal. 

**Plugin Config:**

`{
    "name": "WyzeRoboVac",
    "username": "",
    "password": "",
    "key_id": "",
    "api_key": "",
    "statusCheckRefreshInterval": 15,
    "idleBatteryCheckRefreshInterval": 751,
    "busyBatteryCheckRefreshInterval": 120,
    "path2py_stubs": "/usr/local/lib/node_modules/homebridge-wyze-robovac/py_helpers",
    "debugLevel": 0,
    "_bridge": {
        "username": "0E:7C:48:A3:67:15",
        "port": 46277
    },
    "platform": "WyzeRoboVac"
}`

**Environment:**

* **Plugin Version**: V1.5.1
* **Homebridge Version**: V1.7.0
* **Node.js Version**: V20.11.0
* **NPM Version**: Not sure, should be the latest
* **Operating System**: macOS Sonoma 14.3

**Comment by RMCob** [comment]
@drakehomebridge Is this still a problem? Per the plugin README: Be careful to check that the generated keys do not contain any 'shell' special characters like '*' or '|' (vertical bar). If they do, delete the keys (via the web browser interface) and regenerate them.
