### ISSUE TITLE
Error starting to clean

### ISSUE THREAD

**Issue by tigew** [RMCob/homebridge-wyze-robovac#24]
**Describe The Bug:**
Everything imports fine, but when attempting to clean a room or whole house an error occurs.

**To Reproduce:**
Download plugin, enter info, add accessories, attempt to vacuum, error.

**Expected behavior:**
I expect the vacuum to start.

**Logs:**

``` python
[10/16/2024, 4:59:14 PM] [WyzeRoboVac] error: Command failed: python3 /homebridge/node_modules/homebridge-wyze-robovac/py_helpers/vacuumStartSweep.py LOGINEMAIL LOGINPASSWORD  KEYID APIKEY 'Steve' 'All Rooms'
Traceback (most recent call last):
  File "/homebridge/node_modules/homebridge-wyze-robovac/py_helpers/vacuumStartSweep.py", line 54, in <module>
    for room in vacuum.current_map.rooms:
  File "/usr/local/lib/python3.10/dist-packages/wyze_sdk/models/devices/vacuums.py", line 703, in rooms
    return [VacuumMapRoom(**room) for room in map_data['12']]
  File "/usr/local/lib/python3.10/dist-packages/wyze_sdk/models/devices/vacuums.py", line 703, in <listcomp>
    return [VacuumMapRoom(**room) for room in map_data['12']]
TypeError: wyze_sdk.models.devices.vacuums.VacuumMapRoom() argument after ** must be a mapping, not str
```

**Plugin Config:**

```json
{
    "name": "WyzeRoboVac",
    "username": "LOGINEMAIL",
    "password": "LOGINPASSWORD",
    "key_id": "KEYID",
    "api_key": "APIKEY",
    "statusCheckRefreshInterval": 30,
    "idleBatteryCheckRefreshInterval": 1800,
    "busyBatteryCheckRefreshInterval": 120,
    "path2py_stubs": "/homebridge/node_modules/homebridge-wyze-robovac/py_helpers",
    "debugLevel": 0,
    "_bridge": {
        "username": "0E:19:01:CE:F9:7B",
        "port": 55320
    },
    "platform": "WyzeRoboVac"
}
```

**Environment:**

* **Plugin Version**: v1.5.1 
* **Homebridge Version**: [v1.8.4](https://github.com/homebridge)
* **Node.js Version**: v20.18.0
* **NPM Version**: v20.18.0
* **Operating System**: Ubuntu Jammy (22.04.5 LTS)

**Comment by RMCob** [comment]
@tigew Is this still a problem? Did you map the floor with the Wyze app before using the plugin? I cannot reproduce the problem.
